module.exports={
    PRODUCT_COLLECTION:'products',
    USER_COLLECTION:'users',  
    ADMIN_COLLECTION:'admin',
    CATEGORY_COLLECTION:'categories',
    CART_COLLECTION:'cart',
    ORDER_COLLECTION:'order',
    WALLET_COLLECTION:'wallet',
    COUPON_COLLECTION:'coupon',
    OFFER_COLLECTION:'offer',
    WISHLIST_COLLECTION:'wishlist',
    BANNER_COLLECTION:'banner'
}